title: Nguyen Thai Hoc
url: "https://nguyenthaihoc02.com"
baseurl: "/About-Me"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/nguyenthaihoc02"
footer_text: "Page design by Thai Hoc Nguyen"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/About-Me/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
