title: Nguyen Thai Hoc
url: "https://github.com/nguyenthaihoc02"
baseurl: "/About-Me/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id:

footer: yes
footer_url: "https://github.com/nguyenthaihoc02"
footer_text: "Page design by Thai Hoc Nguyen"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About Me"
   link: "/About-Me/"
 - name: "Curriculum Viatae"
   link: "thaihocnguyen_cv.pdf"
 - name: "Repositories"
   link: "https://github.com/nguyenthaihoc02?tab=repositories"
 - name: "Courses"
   link: "course_all/csai_000"
